# Spring application name
spring.application.name: talkscribe-api

# Server port
server.port: 8080

# AWS configuration
aws.region: ${AWS_REGION}

# Logging level
logging.level.org.springframework: INFO
logging.level.com.productdock: DEBUG

# Enable throwing NoHandlerFoundException for non-existing endpoints
spring.mvc.throw-exception-if-no-handler-found: true

# Disable default resource mappings
spring.web.resources.add-mappings: false
