name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-image:
    # Build Docker Image with Buildpack
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Docker image with Spring Boot Buildpacks
        run: |
          ./mvnw spring-boot:build-image \
            -Dspring-boot.build-image.imageName=talkscribe-api:latest

      - name: Save Docker image as artifact
        run: docker save -o talkscribe-api.tar talkscribe-api:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: talkscribe-api-image
          path: talkscribe-api.tar

  push-to-ecr:
    # Push Docker Image to Amazon ECR
    name: Push to ECR
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: talkscribe-api-image
          path: .

      - name: Load Docker image
        run: docker load -i talkscribe-api.tar

      - name: Log in to Amazon ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URL }}

      - name: Tag Docker image for ECR
        run: docker tag talkscribe-api:latest ${{ secrets.ECR_REPOSITORY_URL }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_REPOSITORY_URL }}:latest

      - name: Docker Cleanup
        run: docker system prune -af
