name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  # Build the JAR file
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: talkscribe-api-jar
          path: target/*.jar

  # Build the Docker image
  build-docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: talkscribe-api-jar
          path: target/

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Image
        run: |
          docker-compose build
          docker tag talkscribe-api-image:latest talkscribe-api:latest

      - name: Save Docker Image as Artifact
        run: docker save -o docker-image.tar talkscribe-api:latest

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar

      - name: Clean Up Docker Image Tarball
        run: rm -f docker-image.tar

  # Push the Docker image to Amazon ECR
  push-to-ecr:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        run: docker load -i docker-image.tar

      - name: Log in to Amazon ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URL }}

      - name: Tag Docker Image
        run: docker tag talkscribe-api:latest ${{ secrets.ECR_REPOSITORY_URL }}:latest

      - name: Push Docker Image to Amazon ECR
        run: docker push ${{ secrets.ECR_REPOSITORY_URL }}:latest
